# Generated by Django 4.2.10 on 2024-02-19 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_mgmt', '0002_customer_itemsales_transaction_store_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos_mgmt.store'),
            preserve_default=False,
        ),
    ]
