# Generated by Django 4.2.10 on 2024-02-21 17:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pos_mgmt", "0003_customer_store_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="itempurchase",
            old_name="price",
            new_name="cost_price",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="org_phone",
            new_name="org_contact",
        ),
        migrations.RemoveField(
            model_name="store",
            name="store_phone",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="min_margin",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="store",
            name="store_contact",
            field=models.CharField(default=980123456, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="itemsales",
            name="quantity",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
